EMAIL = "24f1002193@ds.study.iitm.ac.in"
AIPIPE_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjI0ZjEwMDIxOTNAZHMuc3R1ZHkuaWl0bS5hYy5pbiIsImlhdCI6MTc4NDczOTg3NCwiaXNzIjoiaHR0cHM6Ly9haXBpcGUub3JnIiwiYXVkIjoiYWlwaXBlLWFwaSIsImV4cCI6MTc4NTM0NDY3NH0.zzj85MuZ7XHiwWlQVEdidWk6ZBAB1AFwK7AH3SuQFfY"
AIPIPE_BASE = "https://aipipe.org/openai/v1"
TEXT_MODEL = "gpt-4o-mini"
VISION_MODEL = "gpt-4o"          
EMBED_MODEL = "text-embedding-3-small"
